name: task

on:
  schedule:
    - cron: "0 0 */3 * *"
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  run-chromium:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb chromium-browser tinyproxy-bin
          pip install DrissionPage pyvirtualdisplay requests

      - name: Run Python script to get cookies
        run: |
          sudo python3 script.py ${{ secrets.PROXY }}

      - name: Commit and Push Cookie
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add cookies.json
          git add screenshot.png
          git commit -m 'refresh'
          git push origin main
